config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  root :to  => "users#home"
  get "home/about" => "users#home2"
  resources :users
  get "follower/users/:id" => "users#follower_users",as:"follower_users"
  get "follow/users/:id" => "users#follow_users",as:"follow_users"

  resources :books do
  resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
 end
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
  	has_many :book_comments, dependent: :destroy
  	has_many :favorites, dependent: :destroy
    validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }

 def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
 end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  # validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :books, dependent: :destroy
  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォロー>している人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人


  attachment :profile_image, destroy: false

  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

    # ユーザーをフォローする
    def follow(user_id)
      follower.create(followed_id: user_id)
    end

    # ユーザーのフォローを外す
    def unfollow(user_id)
      follower.find_by(followed_id: user_id).destroy
    end

    # フォローしていればtrueを返す
    def following?(user)
      following_user.include?(user)
    end

end


# favoriteモデルを追加
# 用途：ユーザーと投稿のセットでいいねをしている状態とする
# ユーザーは一つの投稿に一つしかいいねできないこと

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
protected
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  def configure_permitted_parameters
	 devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
	 devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  # def configure_permitted_parameters
  #     devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  # end
end





# 送るカラム名

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
	    @book = Book.find(params[:book_id])
	    @book_comment = current_user.book_comments.new(book_comment_params)
	    @book_comment.book_id = @book.id
	    if @book_comment.save
	       flash[:success] = "Comment was successfully created."
	    end
	    redirect_to request.referer
	end

	def destroy
	@book = Book.find(params[:book_id])
    book_comment = current_user.book_comments.find_by(id: params[:id], book_id: @book.id)
    book_comment.destroy
    redirect_to request.referer
	end

	private

	def book_comment_params
	    params.require(:book_comment).permit(:comment)
	end
end

# 用途：コメントを作成する
# 用途：コメントを削除する
# 自分のコメントしか削除できないこと
# コメント, コメント削除後は行う前の画面に遷移すること
# book_commentモデルを追加 空のコメントは保存できないこと

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def book
  end

  def index
      @user = current_user
      @book = Book.new
      @books =Book.all
      @users =User.all

  end

  def new
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_new = Book.new
    @book_comments = @book.book_comments
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = 'You have creatad book successfully.'
    else
      @user = current_user
      @books =Book.all
      render "index"
    end
  end

  def edit
    @book =Book.find(params[:id])
    redirect_to books_path unless current_user == @book.user
  end

  def update
         @book = Book.find(params[:id])
      if @book.update(book_params)
         redirect_to book_path(@book.id)
         flash[:notice] = "You have updated book successfully."
      else
        render "edit"
      end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :set_book
	def create
    	@favorite = current_user.favorites.new(book_id: @book.id)
    	@favorite.save
	end

	def destroy
	     @favorite = current_user.favorites.find_by(book_id: @book.id)
	     @favorite.destroy
	end
	private
	def set_book
	    @book = Book.find(params[:book_id])
	end
end







# class LikesController < ApplicationController
#   before_action :set_dream

#   def create
#     @like = Like.create(user_id: current_user.id, dream_id: @dream.id)
#   end

#   end

#   private
#   def set_dream
#     @dream = Dream.find(params[:dream_id])
#   end
# end
# コントローラ
# favoritesコントローラを追加@
# createアクションを追加@
# 用途：いいねを作成する
# destroyアクションを追加@
# 用途：いいねを削除する
# いいねを作成, いいねを削除した後は、行う前にいた画面に遷移すること

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
def follow
  current_user.follow(params[:id])
  redirect_to request.referer
end

def unfollow
  current_user.unfollow(params[:id])
  redirect_to request.referer
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:home,:home2]
	def home
	end

	def home2
	end

	def index
		@user = current_user
		@users=User.all
		@book = Book.new
	end

	def show
		@users=User.all
		@user =User.find(params[:id])
		@book_new =Book.new
		@books =@user.books
		@book = Book.new
	end

	def edit
		@user=User.find(params[:id])
		# 下のパラムズで整理したものを受け取る
		# 個人のデータが必要
	  redirect_to user_path(current_user) unless current_user.id == @user.id
	end

	def update
		    user =User.find(params[:id])
	     if user.update(user_params)
	        redirect_to user_path(user.id)
	        flash[:alert] = "You have updated user successfully."
	    else
	    	@user=user
	    	render "edit"
	    end
    end

    def follower_users
    	@users=User.find(params[:id]).follower_user
    end

    def follow_users
    	@users=User.find(params[:id]).following_user
    end
	private
	def user_params
	params.require(:user).permit(:name, :introduction, :profile_image)
	end
end

# show等viewページにつながりるところは⇨@
# 内部操作のみになる場合は⇨@が必要ない
	# params.require(:user).permit(:name, :introduction, :profile_image)これ書くことで受け取るuserの:name,
	 # :introduction, :profile_imageのみ通す

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comment_helper.rb
module BookCommentHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comment/ index.html.erb
<!-- 投稿一覧画面にコメント数を追加 -->

app/views/book_comment/show.html.erb
<!-- 投稿詳細画面に、投稿に対するコメント一覧, コメント数を追加 -->

app/views/books/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete,remote: true do %>
      <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post,remote: true do %>
      <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
    <% end %>
  <% end %>

app/views/books/_form.html.erb
          <%= notice %>
          <%= alert %>
          <h2>User info</h2>
          <div>
             <table class="table table-inverse">
                  <thead>
                    <tr>
                      <th><%= attachment_image_tag user, :profile_image, fallback: "no-image.jpg", size:'100x100' %></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><b>name</b></td>
                      <td><%= user.name %></td>
                    </tr>
                    <tr>
                      <td><b>introduction</b></td>
                      <td><%= user.introduction %></td>
                    </tr>
                         <tr>
                          <td><b>follows</b></td>
                          <td><%= user.follower.count %></td>
                        </tr>
                         <tr>
                          <td><b>followers</b></td>
                          <td><%= user.followed.count %></td>
                        </tr>
             </table>
             <span class="btn btn-default btn-block col-xs-12"><%=link_to"",edit_user_path(user.id),class: "glyphicon glyphicon-wrench"%></span>
          </div>


          <div>
            <h3>New book</h3>
            <%= form_for(book) do |f| %>
              <h5 >Title</h5>
               <%= f.text_field :title ,class: "col-xs-12 book_title"%>
              <h5>Body</h5>
              <%= f.text_area :body ,class: "col-xs-12 book_body"%>
              <%= f.submit 'Create Book', class:"btn btn-primary btn-block"%>
            <% end %>
          </div>



<!-- 先ほど部分テンプレートで、@bookをbookに変更したため今回使用するのはbookになっている。ここからコントローラーに送られる -->

app/views/books/_show.html.erb
     <!-- いいね機能 -->
            <td>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete,remote: true do %>
                  <span class="glyphicon glyphicon-heart"><%= @book.favorites.count%></span>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book), method: :post,remote: true do %>
                  <span class="glyphicon glyphicon-heart-empty"><%= @book.favorites.count %></span>
                <% end %>
              <% end %>
           </td>
      <!-- いいね機能 -->
<!-- 
      あとで別のところを入れる -->

app/views/books/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6" >
          <%= notice %>
            <h1>Editing Book</h1>

             <% if @book.errors.any? %>
                <div class="alert alert-warning">
                  <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
                  <ul>
                    <% @book.errors.full_messages.each do |error| %>
                      <li><%= error %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

            <div>
                <%= form_for @book do |f| %>
                  <h5>Title</h5>
                    <%= f.text_field :title, class: "col-xs-12 book_title" %>
                  <h5>Body</h5>
                  <%= f.text_area :body, class: "col-xs-12 book_body" %>
                  <br>
                  <%= f.submit 'Update Book', class:"btn btn-primary btn-block"%>
                <% end %>
                 <br>
                <%=link_to"Show" ,book_path(@book.id) %> | 
                <%=link_to"Back",books_path%>
            </div>
      </div>
    </div>
</div>

app/views/books/home.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6" >
<div>
	<h1>welcome to <span class="glyphicon glyphicon-book"></span>Bookers !!</h1>
	<p>In <span class="glyphicon glyphicon-book">Bookers,</span></p>
	<p>you can share and exchange your opinions , inpressions , and emotions
	<br>about various books!</p>
  <div class="btn-wrapper" >
  	<div class="row">
	<%=link_to"Log in" ,new_user_session_path,class: "btn btn-info col-xs-10 col-xs-offset-1 login"%>
    </div>
    <div class="row">
	<%=link_to"Sign Up" ,new_user_registration_path,class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up"%>
	</div>
	<div id="right-chomp">&copy;Infratop.inc</div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
              <% if @book.errors.any? %>
                <div class="alert alert-warning">
                  <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
                  <ul>
                    <% @book.errors.full_messages.each do |error| %>
                      <li><%= error %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
    <div class="row">
              <div class="col-xs-3">
                    <%= render 'books/form', book: @book,user: @user %>
              </div>
            <div class="col-xs-9">
                <h2>Books</h2>
                <table class="table table-inverse">
                  <thead>
                    <tr>
                      <th></th>
                      <th><b>Title</b></th>
                      <th><b>Opinion</b></th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
                      <% @books.each do |book| %>
                         <tr>
                          <td>
                           <%= link_to user_path(book.user.id) do %>
                             <%= attachment_image_tag(book.user, :profile_image, fallback: "no-image.jpg", size:'50x50') %>
                           <% end %>
                          </td>
                             <td><%=link_to book.title,book_path(book.id) %></td>
                             <td><%= book.body %></td>


                          <td>
                          <td id="favorites<%= book.id %>">
                          <%= render 'books/favorites', book:book%>
                          </td>
                          <!-- いいね機能 -->
                          <td>コメント数：<%= book.book_comments.count %></td>
                        </tr>
                      <% end %>
                 </tbody>
              </table>
         </div>
    </div>
 </div>

app/views/books/show.html.erb
<div class ="container">
    <div class="row">
              <div class="col-xs-3">
                <%= render 'books/form', book: @book_new,user: @book.user %>
               </div>
           <div class="col-xs-9">
               <h1>Book detail</h1>
                <table class="table table-hover table-inverse">
                    <thead>
                      <tr>
                        <th></th>
                        <th><b>Title</b></th>
                        <th><b>Opinion</b></th>
                        <th colsoan="3"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                          <td>
                           <%= link_to user_path(@book.user) do %>
                             <%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpg", size:'50x50'%>
                             <br>
                             <%= @book.user.name %>
                           <% end %>
                         </td>
                         <td><%= link_to @book.title,book_path(@book) %></td>
                         <td><%= @book.body %></td>

                    <!-- いいね機能 -->
                         <td>
                          <td id="favorites<%= @book.id %>">
                          <%= render 'books/favorites', book:@book%>
                          </td>
                  <!-- いいね機能 -->
                  <!-- コメント件数 -->
                      <td>コメント数:<%= @book.book_comments.count %></td>
                   <!-- コメント件数 -->

                     <%if current_user == @book.user%>
                     <td><%= link_to"Edit",edit_book_path(@book),class:"btn btn-primary"%></td>
                     <td><%= link_to"Destroy",book_path(@book),class:"btn btn-primary" ,method: :delete%></td>
                 <% end %>
                </tr>
           </table>
              <table>
                  <!-- コメント入力欄 -->
                        <% @book_comments.each do |book_comment| %>
                        <tr>
                          <td>
                            <%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
                            <%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpg", size:'50x50' %><br>
                            <%= book_comment.user.name %>
                            <%end%>
                          </td>
                  <!-- コメント入力欄 -->
                        <!-- 削除ボタン -->
                         <td><%= @book_comment.comment %></td>
                         <% if book_comment.user == current_user %>
                         <td><%= link_to "削除", book_book_comment_path(@book,book_comment), method: :delete, class: "btn btn-danger pull-right" %></td>
                         <% end %>
                        </tr>
                        <% end %>
                         <!-- 削除ボタン -->
              </table>
                    <!-- <form class="mt-20"> -->
                    <div>
                      <%= form_for [@book, @book_comment] do |f| %>
                        <%= f.text_area :comment, size: "90*5" %>
                        <%= f.submit "送信", class: "btn btn-sm btn-primary" %>
                      <% end %>
                    </div>
                   <!-- </form> -->
          </div>
    </div>
</div>

app/views/favorites/create.js.erb
$("#favorites<%= @book.id %>").html("<%= j(render partial: 'books/favorites', locals: { book: @book }) %>");

app/views/favorites/destroy.js.erb
$("#favorites<%= @book.id %>").html("<%= j(render partial: 'books/favorites', locals: { book: @book }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<header class="navbar navbar-inverse">
   <nav class="nav navbar-nav navbar-left">
    <h4 style="color:white">Bookers</h4>
   </nav>
    <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user) do %>
                <span class="glyphicon glyphicon-home home">Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user">Users</span>
            <% end %>
            <li>
             <%= link_to books_path do %>
             <span class="glyphicon glyphicon-book">Books</span>
            <% end %>
            </li>
            <li>
            <%= link_to destroy_user_session_path do %>
            <span class="glyphicon glyphicon-log-in"> logout</span>
            <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path do %>
              <span class="glyphicon glyphicon-home"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path do %>
              <span class="glyphicon glyphicon-link"> About</span>
              <% end %>
           </li>
           <li>
              <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-edit"> Sign up</span>
              <% end %>
           </li>
            <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"> login</span>
            <% end %>
          </li>
          <% end %>
        </ul>
    </nav>
</header>
<div class="container">
    <%= yield %>
</div>
    <div class="right-chomp">&copy;Infratop.inc</div>
  </body>
</html>

app/views/users/_user.html.erb
<h2>User info</h2>
     <table class="table table-inverse">
          <thead>
            <tr>
              <th><%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpg", size:'100x100' %></th>
            </tr>
          </thead>
          <tbody>
                <tr>
                  <td><b>name</b></td>
                  <td><%= @user.name %></td>
                </tr>
                <tr>
                  <td><b>introduction</b></td>
                  <td><%= @user.introduction %></td>
                </tr>
                 <tr>
                  <td><b>follows</b></td>
                  <td>
                    <%= link_to follow_users_path(user.id)do %>
                      <%= @user.follower.count %>
                    <% end %>
                  </td>
                </tr>
                 <tr>
                  <td><b>followers</b></td>
                  <td>
                    <%= link_to follower_users_path(user.id) do %>
                      <%= @user.followed.count %>
                    <% end %>
                  </td>
                </tr>
           <tbody>
     </table>
     <div class="btn btn-success">
           <% unless current_user==user %>
           <% if current_user.following?(user) %>
               <%= link_to 'フォロー外す', unfollow_path(user.id), method: :delete %>
           <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
           <% end %>
    <% end %>
     </div>
     <div>
        <h3>New book</h3>
        <%= form_for(@book) do |f| %>
          <h5 >Title</h5>
          <%= f.text_field :title ,class: "col-xs-12 book_title"%>
          <h5>Body</h5>
          <%= f.text_area :body ,class: "col-xs-12 book_body"%>
          <%= f.submit 'Create Book', class:"btn btn-primary btn-block"%>
        <% end %>
     </div>

app/views/users/_users.html.erb
<h2>Users</h2>
      <table class="table table-inverse">
            <thead>
              <tr>
                <th>image</th>
                <th><b>name</b></th>
                <th></th>
                <th colsoan="3"></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <% @users.each do |user| %>
                <td><div><%= attachment_image_tag user, :profile_image, fallback: "no-image.jpg", size:'50x50' %></div></td>
                  <td><%= user.name %></td>
                  <td>フォロー数:<%= user.follower.count %></td>
                  <td>フォロワー数:<%= user.followed.count %></td>
                  <td>
                    <% unless current_user==user %>
                        <% if current_user.following?(user) %>
                            <%= link_to 'フォロー外す', unfollow_path(user.id), method: :delete %>
                          <% else %>
                            <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                      <% end %>
                    <% end %>
                  </td>
                  <td><%=link_to "Show",user_path(user.id)%></td>
              </tr>
                <% end %>
            </tbody>
      </table>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6" >
				<h1>User info</h1>

			 <% if @user.errors.any? %>
              <div class="alert alert-warning">
                <h2><%= @user.errors.count %>errors prohibited this book from being saved:</h2>
                <ul>
                  <% @user.errors.full_messages.each do |error| %>
                    <li><%= error %></li>
                  <% end %>
                </ul>
              </div>
              <% end %>
				<!-- form_for部分 -->
				<div>
					<%= form_for(@user) do |f| %>
					  <span><b>Name</b> <%= f.text_field :name%></span>
					  <p><b>Image</b></p>
					  <%= f.attachment_field :profile_image %>
					  <br>
					  <span><b>Introduction</b> <%= f.text_area :introduction %></span>
					  <!-- 追加部分 -->
					  <br>
					  <br>
					<%= f.submit %>
				<% end %>
       </div>
    </div>
</div>

app/views/users/follow_users.html.erb
<div class="col-xs-12">
<%= render 'users/users', users: @users %>
</div>

app/views/users/follower_users.html.erb
<div class="col-xs-12">
<%= render 'users/users', users: @users %>
</div>

app/views/users/home.html.erb
   <%= notice %>
	<div class="container">
		<div class="row">
			<div class="col-md-offset-3 col-md-6" >

				<h1>welcome to <span class="glyphicon glyphicon-book">Bookers !!</span></h1>
				<p>In <span class="glyphicon glyphicon-book"><b>Bookers,</b></span></p>
				<p>you can share and exchange your opinions , inpressions , and emotions
				<br>about various books!</p>
					<button class="btn btn-info btn-block">
					   <%=link_to"Log in" ,new_user_session_path %>
					</button>
					<button class="btn btn-success btn-block">
					   <%=link_to"Sign Up" ,new_user_registration_path %>
					</button> 
			  </div>
			</div>
		</div>
   </div>

app/views/users/home2.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book"><b>Bookers !</b></span></h1>

app/views/users/index.html.erb
<div class ="container">
    <div class="row">
            <div class="col-xs-3">
<h2>User info</h2>
          <div>
             <table class="table table-inverse">
                  <thead>
                    <tr>
                      <th><%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpg", size:'100x100' %></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><b>@name</b></td>
                      <td><%= @user.name %></td>
                    </tr>
                    <tr>
                      <td><b>introduction</b></td>
                      <td><%= @user.introduction %></td>
                    </tr>
                         <tr>
                          <td><b>follows</b></td>
                          <td><%= @user.follower.count %></td>
                        </tr>
                         <tr>
                          <td><b>followers</b></td>
                          <td><%= @user.followed.count %></td>
                        </tr>
             </table>
             <span class="btn btn-default btn-block col-xs-12"><%=link_to"",edit_user_path(@user.id),class: "glyphicon glyphicon-wrench"%></span>
          </div>


          <div>
            <h3>New book</h3>
            <%= form_for(@book) do |f| %>
              <h5 >Title</h5>
               <%= f.text_field :title ,class: "col-xs-12 book_title"%>
              <h5>Body</h5>
              <%= f.text_area :body ,class: "col-xs-12 book_body"%>
              <%= f.submit 'Create Book', class:"btn btn-primary btn-block"%>
            <% end %>
          </div>

            </div>
         <div class="col-xs-9">
              <h2>Users</h2>
              <table class="table table-inverse">
                    <thead>
                      <tr>
                        <th>image</th>
                        <th><b>name</b></th>
                        <th></th>
                        <th colsoan="3"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <% @users.each do |user| %>
                        <td><div><%= attachment_image_tag user, :profile_image, fallback: "no-image.jpg", size:'50x50' %></div></td>
                          <td><%= user.name %></td>
                          <td>フォロー数:<%= user.follower.count %></td>
                          <td>フォロワー数:<%= user.followed.count %></td>
                          <td>
                            <% unless current_user==user %>
                                <% if current_user.following?(user) %>
                                    <%= link_to 'フォロー外す', unfollow_path(user.id), method: :delete %>
                                  <% else %>
                                    <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                              <% end %>
                            <% end %>
                          </td>
                          <td><%=link_to "Show",user_path(user.id)%></td>
                      </tr>
                        <% end %>
                    </tbody>
              </table>
          </div>
    </div>
</div>
<!-- ----------------------------------------------------------------
 -->

app/views/users/show.html.erb
<div class ="container">
 <div class="row">
          <div class="col-xs-3">
            <%= render 'users/user', user: @user,users: @users %>
          </div>
          <div class="col-xs-9">
              <h2>Books</h2>
              <table class="table table-inverse">
                  <thead>
                    <tr>
                      <th></th>
                      <th><b>Title</b></th>
                      <th><b>Opinion</b></th>
                      <th colsoan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
                      <tr>
                          <% @books.each do |book| %>
                            <td><%= link_to book.title,book_path(book.id) %></td>
                            <td><%= book.body %></td>
                          <% end %>
                      </tr>
                    </tbody>
                  </table>
            </div>
　　　　</div>
</div>

<!-- showでBook.newのからのレコードを入れて飛ばしてきたのが、@book⇨@bookを上のbookに変更する。部分テンプレートの場合 -->
<!-- ⇨ここから_form.htmlerbに飛ぶ -->

<!-- ユーザー詳細画面に、コメント数を追加 -->